In [28]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler
from sklearn import metrics 
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB

In [2]:
df=pd.read_excel('spambase.xlsx')
df

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0               0.00               0.64           0.64           0.0   
1               0.21               0.28           0.50           0.0   
2               0.06               0.00           0.71           0.0   
3               0.00               0.00           0.00           0.0   
4               0.00               0.00           0.00           0.0   
...              ...                ...            ...           ...   
4596            0.31               0.00           0.62           0.0   
4597            0.00               0.00           0.00           0.0   
4598            0.30               0.00           0.30           0.0   
4599            0.96               0.00           0.00           0.0   
4600            0.00               0.00           0.65           0.0   

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0              0.32            0.00              0.00                0.00   
1              0.14            0.28              0.21                0.07   
2              1.23            0.19              0.19                0.12   
3              0.63            0.00              0.31                0.63   
4              0.63            0.00              0.31                0.63   
...             ...             ...               ...                 ...   
4596           0.00            0.31              0.00                0.00   
4597           0.00            0.00              0.00                0.00   
4598           0.00            0.00              0.00                0.00   
4599           0.32            0.00              0.00                0.00   
4600           0.00            0.00              0.00                0.00   

      word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0                0.00            0.00  ...        0.000        0.000   
1                0.00            0.94  ...        0.000        0.132   
2                0.64            0.25  ...        0.010        0.143   
3                0.31            0.63  ...        0.000        0.137   
4                0.31            0.63  ...        0.000        0.135   
...               ...             ...  ...          ...          ...   
4596             0.00            0.00  ...        0.000        0.232   
4597             0.00            0.00  ...        0.000        0.000   
4598             0.00            0.00  ...        0.102        0.718   
4599             0.00            0.00  ...        0.000        0.057   
4600             0.00            0.00  ...        0.000        0.000   

      char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0             0.0        0.778        0.000        0.000   
1             0.0        0.372        0.180        0.048   
2             0.0        0.276        0.184        0.010   
3             0.0        0.137        0.000        0.000   
4             0.0        0.135        0.000        0.000   
...           ...          ...          ...          ...   
4596          0.0        0.000        0.000        0.000   
4597          0.0        0.353        0.000        0.000   
4598          0.0        0.000        0.000        0.000   
4599          0.0        0.000        0.000        0.000   
4600          0.0        0.125        0.000        0.000   

      capital_run_length_average  capital_run_length_longest  \
0                          3.756                          61   
1                          5.114                         101   
2                          9.821                         485   
3                          3.537                          40   
4                          3.537                          40   
...                          ...                         ...   
4596                       1.142                           3   
4597                       1.555                           4   
4598                       1.404                      

In [39]:
X = df.iloc[:, :56].values
y = df.iloc[:, 57].values
X

array([[0.000e+00, 6.400e-01, 6.400e-01, ..., 0.000e+00, 3.756e+00,
        6.100e+01],
       [2.100e-01, 2.800e-01, 5.000e-01, ..., 4.800e-02, 5.114e+00,
        1.010e+02],
       [6.000e-02, 0.000e+00, 7.100e-01, ..., 1.000e-02, 9.821e+00,
        4.850e+02],
       ...,
       [3.000e-01, 0.000e+00, 3.000e-01, ..., 0.000e+00, 1.404e+00,
        6.000e+00],
       [9.600e-01, 0.000e+00, 0.000e+00, ..., 0.000e+00, 1.147e+00,
        5.000e+00],
       [0.000e+00, 0.000e+00, 6.500e-01, ..., 0.000e+00, 1.250e+00,
        5.000e+00]])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

In [8]:
model = GaussianNB() 
model.fit(X_train, y_train)
model.score(X_train, y_train)

0.8282608695652174

In [9]:
y_pred = model.predict(X_test)

In [10]:
print("GNB model accuracy without S.Scaler(in %):", metrics.accuracy_score(y_test, y_pred)*100)

GNB model accuracy without S.Scaler(in %): 81.10065170166546


In [11]:
print(confusion_matrix(y_test,y_pred))

[[598 224]
 [ 37 522]]


In [12]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.73      0.82       822
           1       0.70      0.93      0.80       559

    accuracy                           0.81      1381
   macro avg       0.82      0.83      0.81      1381
weighted avg       0.84      0.81      0.81      1381



In [29]:
model = BernoulliNB()
model.fit(X_train, y_train)
model.score(X_train, y_train)

0.8894409937888199

In [30]:
y_pred = model.predict(X_test)

In [31]:
print("BNB model accuracy(in %):",accuracy_score(y_test, y_pred)*100)

BNB model accuracy(in %): 87.54525706010138


In [32]:
print(confusion_matrix(y_test,y_pred))

[[769  53]
 [119 440]]


In [33]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.94      0.90       822
           1       0.89      0.79      0.84       559

    accuracy                           0.88      1381
   macro avg       0.88      0.86      0.87      1381
weighted avg       0.88      0.88      0.87      1381



In [34]:
model = MultinomialNB()
model.fit(X_train, y_train)
model.score(X_train, y_train)

0.8440993788819876

In [35]:
y_pred = model.predict(X_test)

In [40]:
print("MNB model accuracy(in %):",accuracy_score(y_test, y_pred)*100)

MNB model accuracy(in %): 84.79362780593772


In [41]:
print(confusion_matrix(y_test,y_pred))

[[708 114]
 [ 96 463]]


In [42]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.86      0.87       822
           1       0.80      0.83      0.82       559

    accuracy                           0.85      1381
   macro avg       0.84      0.84      0.84      1381
weighted avg       0.85      0.85      0.85      1381

